---
version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - $API_PORT:8080
    stdin_open: true
    tty: true
    volumes:
      - .:/api-mock
    command: /bin/bash -c "go run main.go"
